Repository Omkar-Sonawane-23/VedicVani, pull requests merged in 2024-05, with the labels that each got.

#42 Fix/navbar overflow 10
  package.json
  public/index.html
  src/App.js
  src/components/AppLayout.js
  src/components/Chapters.js
  src/components/Homeque.js
  src/components/Navbar.js
  src/pages/Home.js
Labels: GSSOC24

#72 fixed go button issue #26
  src/pages/Home.js
Labels: GSSOC24, Level 2

#77 Added animation
  src/pages/Home.js
  src/pages/home.css
Labels: GSSOC24, Level 1

#78 Fixed Container Color and Align Navbar Items issue no #40
  Backend/node_modules/.bin/mime
  src/App.css
  src/components/Navbar.js
Labels: GSSOC24, Level 1

#85 home page logo aligned #50 issue
  src/pages/Home.js
Labels: GSSOC24, Level 1

#119 Introduced Loading Animation for Next/Generate Buttons
  src/components/Chapters.js
  src/components/Homeque.js
  src/pages/Home.js
Labels: GSSOC24

#133 Added the responsive ness in the website
  src/components/Homeque.js
  src/components/Navbar.js
  src/pages/Home.js
Labels: GSSOC24, Level 2

#147 about page ui enhanced
  public/bhagvatgita.jpg
  public/god.jpg
  public/mission.jpg
  src/components/AboutUs.js
Labels: GSSOC24, Level 2

#96 Added buttons in chapters ( Closing issue #80)
  src/components/Chapters.js
Labels: GSSOC24, level2

#153 Closes #118
  package-lock.json
  package.json
  src/App.js
  src/components/Navbar.js
  src/components/Preloader.js
  src/components/krishnaflute.mp3
  src/components/style.css
  src/pages/Home.js
Labels: GSSOC24, level2

#169 [Feature] : Implement the Contact Page
  src/App.js
  src/assets/images/Contact us-amico.png
  src/assets/images/Contact us.gif
  src/assets/images/contact.png
  src/components/Navbar.js
  src/components/style.css
  src/index.js
  src/pages/Contact.js
Labels: GSSOC24, level3

#163 REDESIGNED DROPDOWN
  .gitignore
  src/pages/Home.js
  src/pages/home.css
Labels: GSSOC24, level1

#125 updated favicon
  public/favicon.ico
  public/feather.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/peacock-feather.png
Labels: GSSOC24, level1
